<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <UseUwp>true</UseUwp>
    <Platforms>x86;x64;arm64</Platforms>
    <DefaultLanguage>en-US</DefaultLanguage>
    <IsAotCompatible>true</IsAotCompatible>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <RootNamespace>SimplePad.Search</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Uwp.Animations" Version="8.2.251219" />
    <PackageReference Include="Microsoft.UI.Xaml" Version="2.8.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.Core.UWP\SimplePad.Core.UWP.csproj" />
    <ProjectReference Include="..\SimplePad.Search\SimplePad.Search.csproj" />
  </ItemGroup>
</Project>
