<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>SimplePad.Tabs</RootNamespace>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="AppTabView.xaml" />
    <None Remove="AppTabViewItem.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.Core.WinUI\SimplePad.Core.WinUI.csproj" />
    <ProjectReference Include="..\SimplePad.Editor.WinUI\SimplePad.Editor.WinUI.csproj" />
    <ProjectReference Include="..\SimplePad.Menu.WinUI\SimplePad.Menu.WinUI.csproj" />
    <ProjectReference Include="..\SimplePad.Settings.WinUI\SimplePad.Settings.WinUI.csproj" />
    <ProjectReference Include="..\SimplePad.Settings\SimplePad.Settings.csproj" />
    <ProjectReference Include="..\SimplePad.StatusBar.WinUI\SimplePad.StatusBar.WinUI.csproj" />
    <ProjectReference Include="..\SimplePad.Tabs\SimplePad.Tabs.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="AppTabViewItem.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="AppTabView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
</Project>