<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>SimplePad.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.Core\SimplePad.Core.csproj" />
    <ProjectReference Include="..\SimplePad.Fonts\SimplePad.Fonts.csproj" />
    <ProjectReference Include="..\SimplePad.Windowing.WPF\SimplePad.Windowing.WPF.csproj" />
  </ItemGroup>
</Project>