<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SimplePad.Windowing</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.File.Avalonia\SimplePad.File.Avalonia.csproj" />
    <ProjectReference Include="..\SimplePad.Search.Avalonia\SimplePad.Search.Avalonia.csproj" />
    <ProjectReference Include="..\SimplePad.Settings.Avalonia\SimplePad.Settings.Avalonia.csproj" />
    <ProjectReference Include="..\SimplePad.Tabs.Avalonia\SimplePad.Tabs.Avalonia.csproj" />
    <ProjectReference Include="..\SimplePad.Windowing\SimplePad.Windowing.csproj" />
  </ItemGroup>
</Project>