<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <UseUwp>true</UseUwp>
    <Platforms>x86;x64;arm64</Platforms>
    <DefaultLanguage>en-US</DefaultLanguage>
    <IsAotCompatible>true</IsAotCompatible>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <RootNamespace>SimplePad.Settings</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Uwp.Controls.SettingsControls" Version="8.2.251219" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.Editor.Settings.UWP\SimplePad.Editor.Settings.UWP.csproj" />
    <ProjectReference Include="..\SimplePad.Fonts.Settings.UWP\SimplePad.Fonts.Settings.UWP.csproj" />
    <ProjectReference Include="..\SimplePad.Settings\SimplePad.Settings.csproj" />
    <ProjectReference Include="..\SimplePad.Tabs.Settings.UWP\SimplePad.Tabs.Settings.UWP.csproj" />
    <ProjectReference Include="..\SimplePad.Themes.Settings.UWP\SimplePad.Themes.Settings.UWP.csproj" />
  </ItemGroup>
</Project>
