<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <UseUwp>true</UseUwp>
    <DefaultLanguage>en-US</DefaultLanguage>
    <IsAotCompatible>true</IsAotCompatible>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="UTF.Unknown" Version="2.6.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.Core\SimplePad.Core.csproj" />
    <ProjectReference Include="..\SimplePad.Services\SimplePad.Services.csproj" />
    <ProjectReference Include="..\SimplePad.Settings\SimplePad.Settings.csproj" />
  </ItemGroup>
</Project>
