<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SimplePad.Settings</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAvaloniaUI" Version="3.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.Settings\SimplePad.Settings.csproj" />
  </ItemGroup>
</Project>