<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <UseUwp>true</UseUwp>
    <DefaultLanguage>en-US</DefaultLanguage>
    <IsAotCompatible>true</IsAotCompatible>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.UI.Xaml" Version="2.8.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.Core.UWP\SimplePad.Core.UWP.csproj" />
    <ProjectReference Include="..\SimplePad.Editor.UWP\SimplePad.Editor.UWP.csproj" />
    <ProjectReference Include="..\SimplePad.Menu.UWP\SimplePad.Menu.UWP.csproj" />
    <ProjectReference Include="..\SimplePad.MultiTab\SimplePad.MultiTab.csproj" />
    <ProjectReference Include="..\SimplePad.StatusBar.UWP\SimplePad.StatusBar.UWP.csproj" />
  </ItemGroup>
</Project>
