<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <UseUwp>true</UseUwp>
    <DefaultLanguage>en-US</DefaultLanguage>
    <IsAotCompatible>true</IsAotCompatible>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Uwp.Controls.SettingsControls" Version="8.2.251219" />
    <PackageReference Include="Microsoft.UI.Xaml" Version="2.8.7" />
    <PackageReference Include="Win2D.uwp" Version="1.28.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.Core\SimplePad.Core.csproj" />
    <ProjectReference Include="..\SimplePad.Editor.UWP\SimplePad.Editor.UWP.csproj" />
    <ProjectReference Include="..\SimplePad.Fonts.UWP\SimplePad.Fonts.UWP.csproj" />
    <ProjectReference Include="..\SimplePad.MultiTab.UWP\SimplePad.MultiTab.UWP.csproj" />
    <ProjectReference Include="..\SimplePad.Services.UWP\SimplePad.Services.UWP.csproj" />
    <ProjectReference Include="..\SimplePad.Settings\SimplePad.Settings.csproj" />
    <ProjectReference Include="..\SimplePad.StatusBar.UWP\SimplePad.StatusBar.UWP.csproj" />
    <ProjectReference Include="..\SimplePad.Themes.UWP\SimplePad.Themes.UWP.csproj" />
    <ProjectReference Include="..\SimplePad.ViewModels\SimplePad.ViewModels.csproj" />
  </ItemGroup>
</Project>
