<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>SimplePad.Windowing</RootNamespace>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="ShellWindow.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1839" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.File.WinUI\SimplePad.File.WinUI.csproj" />
    <ProjectReference Include="..\SimplePad.Search.WinUI\SimplePad.Search.WinUI.csproj" />
    <ProjectReference Include="..\SimplePad.Settings.WinUI\SimplePad.Settings.WinUI.csproj" />
    <ProjectReference Include="..\SimplePad.Tabs.WinUI\SimplePad.Tabs.WinUI.csproj" />
    <ProjectReference Include="..\SimplePad.Themes.WinUI\SimplePad.Themes.WinUI.csproj" />
    <ProjectReference Include="..\SimplePad.Windowing\SimplePad.Windowing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="ShellWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
</Project>