<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>SimplePad.Editor</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.Editor\SimplePad.Editor.csproj" />
    <ProjectReference Include="..\SimplePad.Fonts.WPF\SimplePad.Fonts.WPF.csproj" />
  </ItemGroup>
</Project>