<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SimplePad.Fonts.TestApp</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.Fonts.Settings.WPF\SimplePad.Fonts.Settings.WPF.csproj" />
  </ItemGroup>
</Project>