<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>SimplePad.Menu</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.Editor\SimplePad.Editor.csproj" />
  </ItemGroup>
</Project>