<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>SimplePad.Windowing</RootNamespace>
    <NoWarn>$(NoWarn);WPF0001</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplePad.Search.WPF\SimplePad.Search.WPF.csproj" />
    <ProjectReference Include="..\SimplePad.Settings.WPF\SimplePad.Settings.WPF.csproj" />
    <ProjectReference Include="..\SimplePad.Tabs.WPF\SimplePad.Tabs.WPF.csproj" />
    <ProjectReference Include="..\SimplePad.Themes.WPF\SimplePad.Themes.WPF.csproj" />
    <ProjectReference Include="..\SimplePad.Windowing\SimplePad.Windowing.csproj" />
  </ItemGroup>
</Project>